version: '3.7'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example

