version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: qwerty123
    ports:
      - 5432:5432